# Generated by Django 5.0.6 on 2024-06-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(choices=[('AUTHOR', 'Автор'), ('Moderator', 'Модер'), ('Operator', 'Оператор'), ('Reader', 'Пользователь')], default='Reader', verbose_name='Роль'),
        ),
    ]
